version: '3.8'

name: 'fakeflix'

services:
  db:
    image: postgres:15-alpine
    container_name: fakeflix-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: